name: single_agent_sim
root: ./
startup_window: crazyflies_start
pre_window: |
  source <%= @settings["setup_name"] %>
  source /root/CrazySim/ros2_ws/install/setup.bash 
  source /opt/ros/humble/setup.bash 
windows:
  - crazyflies_start:
      layout: tiled
      panes:
        - bash ~/ros2_ws/src/roboticsprojects_crazyflie/launch/sitl_multiagent_text.sh -m crazyflie -f $SPAWN_POSE_DOC -w $ENV_NAME
        - waitForCfsGazebo;sleep 2; ros2 launch roboticsprojects_crazyflie single_agent_sim_launch.py