# Named list of all robots
robots:
  cf:
    enabled: true
    uri: udp://0.0.0.0:19850
    initial_position: [0.0, -4.0, 0.0]
    type: cf_sim  # see robot_types

# Definition of the various robot types
robot_types:
  cf_sim:
    motion_capture:
      enabled: false
    big_quad: false
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 10
      custom_topics:
        velocity:
          frequency: 10
          vars: ["kalman.statePX", "kalman.statePY", "kalman.statePZ"]

  cf:
    motion_capture:
      enabled: true
      marker: cf_mpc
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 10
      custom_topics:
        velocity:
          frequency: 10
          vars: ["kalman.statePX", "kalman.statePY", "kalman.statePZ"]

# Global settings for all robots
all:
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 1 # 1: PID, 2: mellinger
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
